version: '3.8'

services:
  metube:
    build: .
    # Or use: image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
    environment:
      # Basic configuration
      - UID=1000
      - GID=1000
      - DOWNLOAD_DIR=/downloads
      - AUDIO_DOWNLOAD_DIR=/downloads/audio
      
      # Spotify Integration (Optional but recommended)
      # Get these from: https://developer.spotify.com/dashboard
      - SPOTIFY_CLIENT_ID=your_spotify_client_id_here
      - SPOTIFY_CLIENT_SECRET=your_spotify_client_secret_here
      
      # Alternative way to set Spotify credentials via YTDL_OPTIONS
      # - YTDL_OPTIONS={"spotify_client_id": "your_id", "spotify_client_secret": "your_secret"}
      
      # Other options
      - OUTPUT_TEMPLATE=%(title)s.%(ext)s
      - OUTPUT_TEMPLATE_PLAYLIST=%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s
      - CUSTOM_DIRS=true
      - CREATE_CUSTOM_DIRS=true
      
      # Performance settings for large Spotify playlists
      - MAX_CONCURRENT_DOWNLOADS=2
      - DOWNLOAD_MODE=limited
      
    # Optional: Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s